#!/bin/bash
# shutdown script stops all the services on the container required to
# run the lab for the safe dissembling of the lab

# Usage of the Script 

# To use stop.sh, run the command
# ./scripts/stop.sh

# stops the Apache service
service apache2 stop
